### PR TITLE
Apotheosis equipment type overrides for GTCEu tools

### PR DESCRIPTION
**Pull request by ProTriforcer**
The following GTCEu tools will be able to get Pickaxe affixes and gems:
- Pickaxes
- Hammers
- Mining hammers
- Drills
- Wrenches
- Electric wrenches
- Wire cutters

Why wrenches and wire cutters? I thought the mining speed bonuses could be nice for them.

The following GTCEu tools will be able to get Shovel affixes and gems:
- Shovels
- Spades

### CODE REVIEW

**Comment by Ghostipedia** [comment]
Please target the correct branch, in this case use the branch I recently pushed to in the github log (the cleanup branch)

**Review by Ghostipedia — CHANGES_REQUESTED** [review]
See comment

**Comment by mrquentin** [comment]
I'm not sure that the `wire_cutters` and `wrench` should be in there. Some affixes could create issues, like the ones who make the tool mine more than one block

**Comment by Ghostipedia** [comment]
fuck uh, target the 0.5.1 dev branch now, whoops sry

**Comment by ProTriforcer** [comment]
> I'm not sure that the `wire_cutters` and `wrench` should be in there. Some affixes could create issues, like the ones who make the tool mine more than one block

Idk, i haven't encountered anything gamebreaking. But you can always just not pick them
Also, the ones, that make the tool mine more than one block, let you break only one by crouching

**Comment by mrquentin** [comment]
> Idk, i haven't encountered anything gamebreaking. But you can always just not pick them
> Also, the ones, that make the tool mine more than one block, let you break only one by crouching

Never count on people doing the good choice. We're gonna get complaints of something that broke and someone think it's a bug.

**Pull request merged**
